name: Generar código desde OpenAPI

on:
  push:
    branches:
      - main

jobs:
  generar-codigo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generar código Python Flask
        run: java -jar openapi-generator-cli.jar generate -i api.yml -g python-flask -o ./openapi_server

      - name: Comprimir resultados
        run: zip -r openapi_server.zip openapi_server

      - name: Subir artefacto generado
        uses: actions/upload-artifact@v4
        with:
          name: openapi_server_zip
          path: openapi_server.zip
